/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tajo_CONSTANTS_H
#define tajo_CONSTANTS_H

#include "tajo_types.h"

namespace apache { namespace tajo { namespace thrift {

class tajoConstants {
 public:
  tajoConstants();

};

extern const tajoConstants g_tajo_constants;

}}} // namespace

#endif
