/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tajo_constants.h"

namespace apache { namespace tajo { namespace thrift {

const tajoConstants g_tajo_constants;

tajoConstants::tajoConstants() {
}

}}} // namespace

